### ISSUE TITLE
MegaHack installer doesn't run when it's supposed to

### ISSUE THREAD

**Issue by ItzKernel** [RoootTheFox/Linux-MegaHack-Installer#1]
I've used this install script on my first Arch install before (about 2021 december - 2022 january), there were no issues with it, everything worked flawlessly. I decided to do a clean install, because i wanted to switch from KDE Plasma & GNOME to awesomewm. After i set everything up, i tried to use the install script again. It didn't really work. I've tried running it in every proton version, reinstalling the game a couple of times, with both megahack v6 and megahack v7. Nothing really took effect.
  
![image](https://user-images.githubusercontent.com/78853728/168457317-a16c6e25-8f17-4ef1-9e3d-a41a97bd57e9.png)

https://user-images.githubusercontent.com/78853728/168456588-ecc243ed-bacf-4a9c-a1ee-360fd5f53e30.mp4

.

**Comment by RoootTheFox** [comment]
That seems odd, going to look into this when I get time.
Just out of curiosity, did you run the game once before starting the MegaHack installer?

**Comment by ItzKernel** [comment]
yep

**Comment by RoootTheFox** [comment]
First of all, sorry for the late response, I have been busy with a few things lately.
Anyways, I have tried reproducing your issue, however I was not able to do so (even after using a new proton prefix by renaming the old one). You can however try using the latest version on the repo and start it with `DEBUG=1` as environment variable and send me the full output of the script. You can also try installing Proton 7.0 which should work fine

**Comment by ItzKernel** [comment]
I pulled the changes and tried installing again with Proton 7.0 and the `DEBUG=1` environment variable.
Here's the result:

https://user-images.githubusercontent.com/78853728/169507067-c7e5ce61-f66a-4894-a2a3-d7d3ef415a13.mp4

**Comment by RoootTheFox** [comment]
This might be related to the fact that you don't have `freetype2` installed on your system (wine complained, it does not do that for me) or a corrupted MegaHack installer (which would explain the page fault (?))

**Comment by ItzKernel** [comment]
![image](https://user-images.githubusercontent.com/78853728/169606250-8bbb9b43-e0ce-45af-8c49-7e6dda8a0578.png)
i already tried reinstalling freetype2, it didn't do anything either. Wine still complains.

Btw I haven't tried using an older installer, because i have no access to those.

**Comment by ItzKernel** [comment]
So I installed lib32-freetype2 too, that wine warning is gone now, but it still crashes.
![image](https://user-images.githubusercontent.com/78853728/169662526-49433d7d-7099-4fbf-8dd2-a7a3351eb095.png)

**Comment by RoootTheFox** [comment]
I honestly don't know what else could be the issue, the only thing I could think about is redownloading MegaHack, but I doubt that will work.

**Comment by ItzKernel** [comment]
Are you sure using just wine instead of proton would do anything? Would it somehow find and recognize the GD folder?

**Comment by RoootTheFox** [comment]
If you run it in the same WINEPREFIX as your GD installation (proton) it will find it, however im pretty sure the issue you are having is a deeper issue and honestly I do not know how to fix it (I dont know how to debug wine applications)

**Comment by ItzKernel** [comment]
Okay, thanks for the help

**Comment by ItzKernel** [comment]
![image](https://user-images.githubusercontent.com/78853728/177057894-28ff9347-96eb-47a4-ad85-eda601adb4e5.png)
new proton version dropped, i can finally run it again. issue resolved

**Comment by ItzKernel** [comment]
oh right, had to call chmod 777 recursively in the gd folder to allow injecting
