### ISSUE TITLE
deb steam seems to not work

### ISSUE THREAD

**Issue by theonekingboo** [RoootTheFox/Linux-MegaHack-Installer#16]
when i try running the script on the deb package of steam it says
 ```
./megahack_installer.sh: line 167: /home/kingboo/.local/share/Steam/steamapps/compatdata/322170/config_info: No such file or directory
(fatal) Could not find Proton directory within config: /home/kingboo/.local/share/Steam/steamapps/compatdata/322170/config_info

```

im guessing this has something to do with the packaging as the number inside the compatdata is different, instead of being 322170 it's 1493710, 

hope this gets resolved @RoootTheFox

**Comment by RoootTheFox** [comment]
did you try copy-pasting the GD path into megahack?

**Comment by theonekingboo** [comment]
@RoootTheFox ok figured out the issue, i downloaded the game into an external drive, which has different file names, but now when i downloaded it on my usr drive, i cannot find the game when i browse the drive megahack, and detecting the game wont work since geometry dash does not open while im running the script

**Comment by theonekingboo** [comment]
![image](https://github.com/RoootTheFox/Linux-MegaHack-Installer/assets/139255943/a26bbf11-db16-48d7-b315-064c7ad41a70)

**Comment by RoootTheFox** [comment]
steamapps > common > Geometry Dash

**Comment by RoootTheFox** [comment]
if you installed it on an external drive, it'll be there - you can find the path by using the button to open the local files folder in steam

**Comment by theonekingboo** [comment]
@RoootTheFox i uninstalled the time i did it with the external drive, it's now installed onto my main drive

**Comment by theonekingboo** [comment]
i'll try the external drive method again tho

**Comment by theonekingboo** [comment]
@RoootTheFox yep installing it in the external drive worked this time by setting the steam path as my external drive, thanks!
