### ISSUE TITLE
Gets stuck on "wine: using kernel write watches, use_kernel_writewatch 2."

### ISSUE THREAD

**Issue by ArchknightO-O** [RoootTheFox/Linux-MegaHack-Installer#18]
![image](https://github.com/RoootTheFox/Linux-MegaHack-Installer/assets/126905458/eea77f28-765c-41db-8bbe-b5161e7426df)
When I go to execute the script, it works fine till here, then just gets stuck. I waited for 20+ minutes, and it still didn't work. Any help is great! :3

**Comment by RoootTheFox** [comment]
not quite sure whats going wrong here. can you provide some more information about your system? (e.g. distro, version of applicable, wine version being used, etc)

**Comment by ArchknightO-O** [comment]
I ended Up getting it working in the end, I just had to reinstall wine. No clue what the issue was. Thanks for the response, I just forgot to close it.

**Comment by ArchknightO-O** [comment]
As a side note, getting it working just meant that I got the installer to run, the menu wouldn't appear in game.

**Comment by RoootTheFox** [comment]
OH - yes that is a known issue, the Xinput stuff is outdated (i forgot to update that) - change `XInput9_1_0` in the overrides to `xinput1_4` @ArchknightO-O

**Comment by RoootTheFox** [comment]
pushed a fix for that in the script; it'll no longer show misinformation ^^

**Comment by ArchknightO-O** [comment]
Thanks so much :3
