### ISSUE TITLE
(fatal) Could not find the file you specified!

### ISSUE THREAD

**Issue by Lu1s06** [RoootTheFox/Linux-MegaHack-Installer#19]
I'm on Arch Linux, I installed the requirements and provided the exact path to the "MegaHackInstaller8.zip" archive.
It will just give me this error: `(fatal) Could not find the file you specified!` and then close. I have a pretty minimal install, are you sure, there aren't any other dependencies I could be missing here?

**Comment by Lu1s06** [comment]
[FIXED]
looking through the script, fzf is required to detect the zip file correctly. Please add as a dependency next to unzip or warn user upon running the script

**Comment by RoootTheFox** [comment]
[this block of code](https://github.com/RoootTheFox/Linux-MegaHack-Installer/blob/main/megahack_installer.sh#L114-L131) should handle the case where fzf isn't installed - in that case, it'll just fall back to using `read -r` to query the path from the user.
is it possible that you dragged the file in your terminal and/or the path had `file://` at the beginning?

**Comment by RoootTheFox** [comment]
hm, that shouldn't break - can you add `printf "-%s-" "$megahack_zip` right below the read line (and temporarily remove fzf) and show me what it outputs?

**Comment by Lu1s06** [comment]
Hey, sorry for the long wait, but I reinstalled my system in the meantime and I'm somehow not able to replicate the issue...
Also I didn't reclone the directory or any files at all, so I really don't know what's going on.

**Comment by RoootTheFox** [comment]
there was probably some sort of whitespace or escape character that somehow ended up in the path entry. good to know that it was likely not a bug though ^^ thanks for reporting either way!!
