### ISSUE TITLE
MegaHack V8 (2.2) support

### ISSUE THREAD

**Issue by githubmanlinus** [RoootTheFox/Linux-MegaHack-Installer#5]
i need

**Comment by RoootTheFox** [comment]
works out of the box from my testing!

**Comment by githubmanlinus** [comment]
oh well then i forgot a dependency or somethig

**Comment by theonekingboo** [comment]
@githubmanlinus does it work now or are you still not able to install?

**Comment by RoootTheFox** [comment]
i plan on reworking this script either way, it's really messy atm and I've also learned some new things since i wrote the original thing.

(there's also some very much unneeded dependencies to sort out)

**Comment by RoootTheFox** [comment]
I've reworked a lot of the script, including adding support for fancy file picking through `fzf`, adding colors, generally improving the script to make it easier to use, improving the proton path finding logic (thanks Jeremy in #7!) and also removing the long unused p7zip dependency.

@githubmanlinus can you try again and report back here?

**Comment by githubmanlinus** [comment]
yea i just a forgot a dependency

**Comment by githubmanlinus** [comment]
it works now
