### ISSUE TITLE
Requirement

### ISSUE THREAD

**Issue by Na0ss** [RoootTheFox/Linux-MegaHack-Installer#9]
Hey! What is unzip and what do you mean by changing the directory to ... ?

**Comment by RoootTheFox** [comment]
`unzip` is a command needed for extracting the megahack zip - try just running the script using the command in the README, if it's missing it will tell you!

(side note, what distro are you using?)

**Comment by Na0ss** [comment]
Hey ! the script worked but actually it sais smt like "paste in the exe selection window" but whats the exe selection window ?
And im using Ubuntu 22.04!

**Comment by Na0ss** [comment]
![image](https://github.com/RoootTheFox/Linux-MegaHack-Installer/assets/126100606/4c02eb66-b155-4a8f-9507-80d993b707e7)

**Comment by RoootTheFox** [comment]
Did the MegaHack installer window open?
If yes; there's a field in the installer where you have to navigate to the GD exe. The path is shown in the script - "Path to GD exe: "

**Comment by theonekingboo** [comment]
@Na0ss did you ever get this resolved?

**Comment by RoootTheFox** [comment]
since there's not been any activity, i'm gonna close this for now. if the issue persists, feel free to reopen!
